main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('plan/', views.plan, name='plan'),
    path('article/', views.article, name='article'),
    path('article_pub/', views.article_pub, name='article_pub'),
]

webplatform/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from users.views import change_password, update_user_info
from institutions.views import institute, department
from django.conf.urls.static import static
from django.conf import settings
from main.views import plan, article

urlpatterns = [
    path('admin/', admin.site.urls),
    # Main Page
    path('', include('main.urls')),
    path('login/', user_views.user_login, name='login'),
    path('logout/', user_views.user_logout, name='logout'),
    path('changepassword/', change_password, name='change-password'),
    path('update_user_info/', update_user_info, name='update-user-info'),
    #  Institution
    path('institute/', institute, name='institute'),
    #  Department
    path('department/', department, name='department'),

    path('project/', include('projects.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

institutions/models.py
from django.db import models
from users.models import Account
from constant.models import Education
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class Institution(models.Model):
    name = models.CharField(max_length=255)
    founded_at = models.DateField()
    disabled = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Муассиса'
        verbose_name_plural = 'Муассисаҳо'

    def __str__(self):
        return self.name

class Department(models.Model):
    name = models.CharField(max_length=255)
    founded_at = models.DateField()
    disabled = models.BooleanField(default=False)
    head = models.OneToOneField(Account, on_delete=models.CASCADE)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Шуъба'
        verbose_name_plural = 'Шуъбаҳо'

    def __str__(self):
        return self.name

class Job(models.Model):
    name = models.CharField(max_length=255)
    capacity = models.PositiveIntegerField(default=1)
    occupied = models.BooleanField(default=False)
    disabled = models.BooleanField(default=False)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    degree_needed = models.ForeignKey(Education, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Вазифа'
        verbose_name_plural = 'Вазифаҳо'

    def __str__(self):
        return self.name

class User_job(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    place = models.DecimalField(max_digits=5, decimal_places=2)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    disabled = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Вазифаи корманд'
        verbose_name_plural = 'Вазифаҳои кормандон'

    def __str__(self):
        return self.user.first_name + '-' + self.job.name + '(' + str(self.place) + ')'

main/models.py
from django.db import models
from users.models import Account
from constant.models import Category
from .validators import validate_file_extension

class Article(models.Model):
    name = models.CharField(max_length=255)
    annotation = models.TextField()
    pages = models.PositiveIntegerField()
    pub_date = models.DateField(null=True, blank=True)
    pub_place = models.CharField(max_length=255, null=True, blank=True)
    pub_link = models.CharField(max_length=255, null=True, blank=True)
    category  = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    author  = models.ForeignKey(Account, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    edited_at = models.DateField(auto_now=True)
    pdf_file = models.FileField(upload_to='static/pdf/scientific', validators=[validate_file_extension], verbose_name='PDF-Файл', null=True, blank=True)

    class Meta:
        verbose_name = 'Мақола'
        verbose_name_plural = 'Мақолаҳо'

    def __str__(self):
        return self.name

class Article_pub(models.Model):
    name = models.CharField(max_length=255)
    pages = models.PositiveIntegerField()
    pub_date = models.DateField(null=True, blank=True)
    pub_place = models.CharField(max_length=255, null=True, blank=True)
    pub_link = models.CharField(max_length=255, null=True, blank=True)
    category  = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    author  = models.ForeignKey(Account, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    edited_at = models.DateField(auto_now=True)
    pdf_file = models.FileField(upload_to='static/pdf/public', validators=[validate_file_extension], verbose_name='PDF-Файл', null=True, blank=True)

    class Meta:
        verbose_name = 'Мақолаи оммавӣ'
        verbose_name_plural = 'Мақолаҳои оммавӣ'

    def __str__(self):
        return self.name

class TV(models.Model):
    topic = models.CharField(max_length=255)
    program_date = models.DateField()
    tv_name = models.CharField(max_length=255)
    tv_program = models.CharField(max_length=255, null=True, blank=True)
    program_link = models.CharField(max_length=255, null=True, blank=True)
    category  = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    author  = models.ForeignKey(Account, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Барномаи телевизионӣ'
        verbose_name_plural = 'Барномаҳои телевизионӣ'

    def __str__(self):
        return self.topic

class Book(models.Model):
    name = models.CharField(max_length=255)
    annotation = models.TextField()
    pages = models.PositiveIntegerField()
    pub_date = models.DateField(null=True, blank=True)
    pub_place = models.CharField(max_length=255, null=True, blank=True)
    pub_link = models.CharField(max_length=255, null=True, blank=True)
    category  = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    author  = models.ForeignKey(Account, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    edited_at = models.DateField(auto_now=True)
    pdf_file = models.FileField(upload_to='static/pdf/books', validators=[validate_file_extension], verbose_name='PDF-Файл', null=True, blank=True)

    class Meta:
        verbose_name = 'Китоб'
        verbose_name_plural = 'Китобҳо'

    def __str__(self):
        return self.name

class Radio(models.Model):
    topic = models.CharField(max_length=255)
    program_date = models.DateField()
    radio_name = models.CharField(max_length=255)
    radio_program = models.CharField(max_length=255, null=True, blank=True)
    program_link = models.CharField(max_length=255, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    author = models.ForeignKey(Account, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Барномаи радиоӣ'
        verbose_name_plural = 'Барномаҳои радиоӣ'

    def __str__(self):
        return self.topic

class Conference(models.Model):
    topic = models.CharField(max_length=255)
    conf_date = models.DateField()
    conf_name = models.CharField(max_length=255)
    conf_place = models.CharField(max_length=255)
    conf_link = models.CharField(max_length=255, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    author = models.ForeignKey(Account, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Конфронсу семинар'
        verbose_name_plural = 'Конфронсу семинарҳо'

    def __str__(self):
        return self.topic

projects/models.py
from django.db import models
from institutions.models import Department
from constant.models import Direction, Category, Status
from users.models import Account

class Project(models.Model):
    name = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField()
    completed = models.BooleanField(default=False)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    direction = models.ForeignKey(Direction, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Лоиҳа'
        verbose_name_plural = 'Лоиҳаҳо'

    def __str__(self):
        return self.name

class Topic(models.Model):
    name = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField()
    taken = models.BooleanField(default=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Мавзуъ'
        verbose_name_plural = 'Мавзуъҳо'

    def __str__(self):
        return self.name



class Plan(models.Model):
    year = models.CharField(max_length=4, verbose_name='Сол')
    aproved = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name='Мавзуъ')
    print_list = models.DecimalField(max_digits=4, decimal_places=2, default=1,  verbose_name='Ҷузъи чопӣ')

    class Meta:
        verbose_name = 'Нақшаи инфродӣ'
        verbose_name_plural = 'Нақшаҳои инфродӣ'
        unique_together = ('user', 'year',)


    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name + '-' + self.year

class Subtopic(models.Model):
    name = models.CharField(max_length=255)
    print_list = models.DecimalField(max_digits=4, decimal_places=2, default=1)
    due_date = models.DateField()
    excepted = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE, default=1)
    plan_id = models.ForeignKey(Plan, on_delete=models.CASCADE)
    article_info = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        ordering = ('due_date',)
        verbose_name = 'Боб'
        verbose_name_plural = 'Бобҳо'

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# from .models import Post
# from users.models import Account

# class RegisterForm(UserCreationForm):
#     email = forms.EmailField(required=True, help_text="Ҳатмист! Лутфан, емайли дурустро ворид созед!!")
#     class Meta:
#         model = Account
#         fields = ["first_name", "last_name", "email", "password1", "password2"]

institutions/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required

@login_required(login_url="login")
def institute(request):
    # current_user_groups = request.user.groups.values_list("name", flat=True)
    context = {
        "not_main": True,
        "is_institute": True
    }
    return render(request, 'main/institute.html', context)

@login_required(login_url="login")
def department(request):
    department = request.user.department
    # print(department)
    context = {
        "not_main": True,
        "department": department
    }
    return render(request, 'main/department.html', context)

main/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.decorators import login_required, permission_required

@login_required(login_url="login")
def home(request):
    current_user_groups = request.user.groups.values_list("name", flat=True)
    context = {
        "is_institute": "institute" in current_user_groups,
        "is_department": "department" in current_user_groups,
    }
    return render(request, 'main/home.html', context)

@login_required(login_url="login")
def plan(request):
    return render(request, 'partials/plan.html')

@login_required(login_url="login")
def article(request):
    return render(request, 'partials/article.html')

@login_required(login_url="login")
def article_pub(request):
    return render(request, 'partials/article_pub.html')

templates/main/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="media/images/main_images/school.png">
    <link rel="stylesheet" type="text/css" href = "{% static 'bootstrap/css/bootstrap.min.css' %}"/>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'htmx/htmx.min.js' %}"></script>

    <title>{% block title %}My WebSite{% endblock %}</title>
  </head>
  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <nav class="container-fluid">
        <div class="row bg-light border-bottom">
            <div class="row col-12 col-md-10">
              <a class="col-12 col-md-2 text-center text-md-end">
                <img src="../media/images/main_images/school.png" class="col-8 col-md-3 w-25 mt-1" alt="Logo">
              </a>
              <div class="row col-12 col-md-10">
                <h5 class="col-12 text-center col-md-10 text-md-start fw-bolder">
                  Иститути омӯзиши масъалаҳои давлатҳои Осиё ва Аврупои АМИТ
                </h5>
                <p class="col-12 text-center col-md-10 text-md-start fw-bolder">
                    {% if not not_main %}
                        Равзанаи пажуҳишгар
                    {% else %}
                        {% if is_institute %}
                            Равзанаи раёсат
                         {% else %}
                            Равзанаи {{department.name}}
                        {% endif %}
                    {% endif %}
                </p>
              </div>
            </div>
            <div class="row col-12 col-md-2">
                <img src="../media/{{user.profile.image}}" class="col-4 m-1" alt="Logo">
                <div class="dropdown col-7 align-self-center text-center m-1">
                    <h5 class="dropdown-toggle" data-bs-toggle="dropdown">
                    {{user.first_name}} {{user.last_name}}
                  </h5>
                  <ul class="dropdown-menu">
                    {% if not_main %}
                    <li class="nav-item">
                      <a class="nav-link link-dark dropdown-item ps-3 pt-2" href="/">Пажуҳишгар</a></li>
                    {% endif %}
                    {% if perms.institutions.add_department and not not_main%}
                    <li class="nav-item">
                      <a class="nav-link link-dark dropdown-item ps-3 pt-2" href="/institute">Институт</a></li>
                    {% endif %}
                    {% if perms.projects.add_project and not not_main and not perms.institutions.add_department %}
                    <li class="nav-item">
                      <a class="nav-link link-dark dropdown-item ps-3 pt-2" href="/department">Шуъба</a></li>
                    {% endif %}
                    {% if not not_main %}
                    <li class="nav-item">
                        <button class="nav-link link-dark dropdown-item ps-3 pt-2" data-bs-toggle="modal" data-bs-target="#modal"
                                hx-get="{% url 'update-user-info' %}" hx-target="#dialog">Профил</button></li>
                    {% endif %}
                    {% if user.is_staff %}
                    <li class="nav-item">
                      <a class="nav-link link-dark dropdown-item ps-3 pt-2" href="/admin" target=”_blank”>Мудирият</a></li>
                    {% endif %}
                    {% if not not_main %}
                    <li class="nav-item">
                        <button class="nav-link link-dark dropdown-item ps-3 pt-2" data-bs-toggle="modal" data-bs-target="#modal"
                                hx-get="{% url 'change-password' %}" hx-target="#dialog"> Ивази рамз</button></li>
                    {% endif %}
                    <li><hr class="dropdown-divider"></hr></li>
                    <li class="nav-item">
                        <a class="nav-link link-dark dropdown-item ps-3 " href="{% url 'logout'%}">Logout</a></li>
                  </ul>
                </div>
            </div>
        </div>
    </nav>
    <div class="container-fluid">{% block content %} {% endblock %}</div>
    <div id="modal" class="modal fade">
      <div id="dialog" class="modal-dialog"></div>
    </div>
  </body>
</html>

templates/main/create_post.html
{% extends 'main/base.html' %} {% block title %}Create a Post{% endblock %} 
{% load crispy_forms_tags %} {% block content %}
<form method="post">
  {% csrf_token %}{{form|crispy}}
  <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

templates/main/department.html
{% extends 'main/base.html' %}
{% block title %}Шуъба{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12 col-md-10 order-2 order-md-1">
        <h4 class="text-center">{{department.head}}</h4>
    </div>

    <div class="col-12 col-md-2 order-1 order-md-2 border-left px-md-0 border-left border border-end-0 border-bottom-0 border-top-0 border-start-md-0">

        <div class="d-flex flex-column w-100">
            <button href="#" class="btn rounded-0 bg-secondary bg-opacity-50 text-dark fw-semibold" style="height:70px">Воҳиди корӣ</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Кормандон</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Нақшаҳои инфиродӣ</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Ҳисобот</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Намояҳо</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Вакансияҳо</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Ҳамкорони собиқ</button>
        </div>

    </div>
</div>
{% endblock %}

templates/main/home.html
{% extends 'main/base.html' %}
{% block title %}АСОСӢ{% endblock %}
{% block content %}
<div class="row">
    <div id = "content" class="col-12 col-md-10 order-2 order-md-1">
    </div>

    <div class="col-12 col-md-2 order-1 order-md-2 border-left px-md-0 border-left border border-end-0 border-bottom-0 border-top-0 border-start-md-0">

        <div class="d-flex flex-column w-100">
            <button class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px"
                hx-get="{% url 'plan' %}" hx-target="#content" hx-trigger="click, load">Нақшаи инфиродӣ</button>
            <button class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px"
                hx-get="{% url 'article' %}" hx-target="#content" hx-trigger="click">Мақолаҳои илмӣ</button>
            <button class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px"
                hx-get="{% url 'article_pub' %}" hx-target="#content" hx-trigger="click">Мақолаҳои оммавӣ</button>
<!--            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Мақолаҳои оммавӣ</button>-->
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Барномаҳои телевизионӣ</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Барномаҳои радиоӣ</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Конфренсу саминарҳо</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Ҳисобот</button>
        </div>

    </div>
</div>
{% endblock %}

templates/main/institute.html
{% extends 'main/base.html' %}
{% block title %}Раёсат{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12 col-md-10 order-2 order-md-1">
        <h4 class="text-center">Content</h4>
    </div>

    <div class="col-12 col-md-2 order-1 order-md-2 border-left px-md-0 border-left border border-end-0 border-bottom-0 border-top-0 border-start-md-0">

        <div class="d-flex flex-column w-100">
            <button href="#" class="btn rounded-0 bg-secondary bg-opacity-50 text-dark fw-semibold" style="height:70px">Воҳиди корӣ</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Лоиҳаҳо</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Кормандон</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">нақшаи инфиродӣ</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Ҳисобот</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Намояҳо</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Китобҳо</button>
        </div>

    </div>
</div>
{% endblock %}

templates/main/institution.html
{% extends 'main/base.html' %}
{% block title %}АСОСӢ{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12 col-md-10 order-2 order-md-1">
        <h4 class="text-center">Content</h4>
    </div>

    <div class="col-12 col-md-2 order-1 order-md-2 border-left px-md-0 border-left border border-end-0 border-bottom-0 border-top-0 border-start-md-0">

        <div class="d-flex flex-column w-100">
            <button href="#" class="btn rounded-0 bg-secondary bg-opacity-50 text-dark fw-semibold" style="height:70px">Воҳиди корӣ</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Лоиҳаҳо</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Кормандон</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">нақшаи инфиродӣ</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Ҳисобот</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Намояҳо</button>
            <button href="#" class="btn rounded-0 bg-light text-dark border border-top-0 border-end-0 border-start-0 fw-semibold" style="height:70px">Китобҳо</button>
        </div>

    </div>
</div>
{% endblock %}